name: flutter_github_repos
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  logger: ^1.1.0
  flutter_screenutil: ^5.5.3+2
  dio: ^4.0.6
  get_storage: ^2.0.3
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  awesome_notifications: ^0.6.21
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  rename_app: ^1.1.0
  iconly: ^1.0.1
  expandable_text: ^2.3.0
  iconsax: ^0.0.8
  api_cache_manager: ^1.0.2
  cached_network_image: ^3.2.1
  loadmore: ^2.0.1
  intl: ^0.17.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.1+1
  flutter_lints: ^2.0.0





flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  background_image: assets/images/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900
